name: local_auth_example
description: Demonstrates how to use the local_auth plugin.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth:
    path: ../
  local_auth_android: ^1.0.46
  local_auth_darwin: ^1.4.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
